import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Tabs from "@/components/Tabs";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex flex-col min-h-screen relative">
          <nav>
            <Navbar />    
          </nav>
          <main className=" mb-40 container mx-auto">
            {children}
            </main>
          <footer  className=" absolute bottom-2 w-full ">
            <Footer/>
          </footer>
        </div>
      </body>
    </html>
  );
}
